/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeumemory;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author mc485207
 */
public class InitDlg extends javax.swing.JDialog {
    private LesJoueurs lj; // les joueurs sélectionnés
    private boolean ok; // indicateur de fermeture
    private int nc; // niveau du jeu (4,10,18,32)
    
    //constructeur standard
    public InitDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);//appel du constructeur de la classe JDialog
        initComponents();//création de l'interface(générée par l'IDE)
        //initialisation des attributs
        this.lj=new LesJoueurs();
        this.ok=false;
        this.nc=4;
    }
    
    //accesseur pour récupérer les joueurs choisis dans la boite de dialogue
    public LesJoueurs getJoueurs() { return this.lj;}
    
    //accesseur pour récupérer l'indicateur de fermeture par le bouton Valider
    public boolean getOk() { return this.ok;}
    
    //accesseur pour récupérer le niveau choisit dans le jeu
    public int getNiveau() {return this.nc;}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        enfant = new javax.swing.JRadioButton();
        débutant = new javax.swing.JRadioButton();
        avancé = new javax.swing.JRadioButton();
        expert = new javax.swing.JRadioButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Lara = new javax.swing.JCheckBox();
        Jack = new javax.swing.JCheckBox();
        Jean = new javax.swing.JCheckBox();
        Amadeus = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        BPhoto = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        jPanel10.setLayout(new java.awt.GridLayout(5, 1));

        jLabel4.setText("Choisissez la taille du jeu");
        jPanel10.add(jLabel4);

        buttonGroup1.add(enfant);
        enfant.setText("enfant(8 cartes)");
        enfant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfantActionPerformed(evt);
            }
        });
        jPanel10.add(enfant);

        buttonGroup1.add(débutant);
        débutant.setText("débutant(20 cartes)");
        débutant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                débutantActionPerformed(evt);
            }
        });
        jPanel10.add(débutant);

        buttonGroup1.add(avancé);
        avancé.setText("avancé(36 cartes)");
        avancé.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avancéActionPerformed(evt);
            }
        });
        jPanel10.add(avancé);

        buttonGroup1.add(expert);
        expert.setText("expert(64 cartes)");
        expert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expertActionPerformed(evt);
            }
        });
        jPanel10.add(expert);

        jPanel6.add(jPanel10);

        jPanel11.setLayout(new java.awt.GridLayout(5, 1));

        jLabel5.setText("Choisissez les joueurs crées");
        jPanel11.add(jLabel5);

        Lara.setText("Lara");
        Lara.setToolTipText("");
        Lara.setDoubleBuffered(true);
        Lara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaraActionPerformed(evt);
            }
        });
        jPanel11.add(Lara);

        Jack.setText("Jack");
        Jack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JackActionPerformed(evt);
            }
        });
        jPanel11.add(Jack);

        Jean.setText("Jean-Sébastien");
        Jean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JeanActionPerformed(evt);
            }
        });
        jPanel11.add(Jean);

        Amadeus.setText("Amadeus");
        Amadeus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmadeusActionPerformed(evt);
            }
        });
        jPanel11.add(Amadeus);

        jPanel6.add(jPanel11);

        getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel7.setLayout(new java.awt.GridLayout(2, 1));

        Edition.setColumns(20);
        Edition.setRows(5);
        jScrollPane4.setViewportView(Edition);

        jPanel7.add(jScrollPane4);

        BPhoto.setPreferredSize(new java.awt.Dimension(240, 320));
        jPanel7.add(BPhoto);

        getContentPane().add(jPanel7, java.awt.BorderLayout.EAST);

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(Valider, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Valider)
                .addComponent(Annuler))
        );

        getContentPane().add(jPanel8, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //gestionnaire du clic sur Valider
    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        this.ok=true;
    setVisible(false);
        dispose();
        
    }//GEN-LAST:event_ValiderActionPerformed
    //gestionnaire du clic sur Annuler
    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        setVisible(false);
        this.ok = false;
    }//GEN-LAST:event_AnnulerActionPerformed
    //gestionnaire du clic sur le bouton radio enfant
    private void enfantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfantActionPerformed
        this.nc=4;
    }//GEN-LAST:event_enfantActionPerformed
    //gestionnaire du clic sur le bouton radio débutant
    private void débutantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_débutantActionPerformed
        this.nc=10;
    }//GEN-LAST:event_débutantActionPerformed
    //gestionnaire du clic sur le bouton radio avancé
    private void avancéActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avancéActionPerformed
        this.nc=18;
    }//GEN-LAST:event_avancéActionPerformed
    //gestionnaire du clic sur le bouton radio expert
    private void expertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expertActionPerformed
        this.nc=32;
    }//GEN-LAST:event_expertActionPerformed
    //gestionnaire du clic sur le case à cocher Lara
    private void LaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaraActionPerformed
      
        Joueur j=new Joueur("Lara", "communs");
        j.setPhoto(new ImageIcon(getClass().getResource("/img/Lara.jpg")));
        Edition.setText(j.toString());
        Image img = j.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);
        BPhoto.setIcon(new ImageIcon(img));
        if(Lara.isSelected())
            this.lj.ajouteJoueur(j);
        else
            this.lj.supprimeJoueur(j);
    }//GEN-LAST:event_LaraActionPerformed
    //gestionnaire du clic sur le case à cocher Jack
    private void JackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JackActionPerformed
        Joueur j=new Joueur("Jack", "rares");
        j.setPhoto(new ImageIcon(getClass().getResource("/img/Jack.png")));
        Edition.setText(j.toString());
        Image img = j.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);
        BPhoto.setIcon(new ImageIcon(img));
        if(Jack.isSelected())
            this.lj.ajouteJoueur(j);
        else
            
            this.lj.supprimeJoueur(j);
    }//GEN-LAST:event_JackActionPerformed
    //gestionnaire du clic sur le case à cocher Jean
    private void JeanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JeanActionPerformed
        Joueur j=new Joueur("Jean", "epiques");        j.setPhoto(new ImageIcon(getClass().getResource("/img/Jean.jpg")));
        Edition.setText(j.toString());
        Image img = j.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);
        BPhoto.setIcon(new ImageIcon(img));
        if(Jean.isSelected())
            this.lj.ajouteJoueur(j);
        else
            this.lj.supprimeJoueur(j);
    }//GEN-LAST:event_JeanActionPerformed
    //gestionnaire du clic sur le case à cocher Amadeus
    private void AmadeusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmadeusActionPerformed
        Joueur j=new Joueur("Amadeus", "legendaires");
        j.setPhoto(new ImageIcon(getClass().getResource("/img/Amadeus.jpg")));
        Edition.setText(j.toString());
        Image img = j.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);
        BPhoto.setIcon(new ImageIcon(img));
        if(Amadeus.isSelected())
            this.lj.ajouteJoueur(j);
        else
            this.lj.supprimeJoueur(j);
    }//GEN-LAST:event_AmadeusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InitDlg dialog = new InitDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Amadeus;
    private javax.swing.JButton Annuler;
    private javax.swing.JButton BPhoto;
    private javax.swing.JTextArea Edition;
    private javax.swing.JCheckBox Jack;
    private javax.swing.JCheckBox Jean;
    private javax.swing.JCheckBox Lara;
    private javax.swing.JButton Valider;
    private javax.swing.JRadioButton avancé;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton débutant;
    private javax.swing.JRadioButton enfant;
    private javax.swing.JRadioButton expert;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
