/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package jeumemory;

import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Yahya
 */
public class VisuJoueursDlg extends javax.swing.JDialog {

    private LesJoueurs lj;//les joueurs à afficher
    
    
    public VisuJoueursDlg(java.awt.Frame parent, boolean modal,LesJoueurs lesj) {
        super(parent, modal);//appel de constructeur de la classe ancètre(JDialog)
        initComponents();//création de l'interface générée par l'EDI
        //initialisation de l'attribut avec le paramètre
        this.lj=lesj;
        //appel de la méthode de création des boutons par les photos
        initTrombi();
    }
    
    public void initTrombi(){
        
        int nb = this.lj.getNbJoueurs();
        //on fixe le layout du panneau avec nb
        Panneau.setLayout(new GridLayout(1,nb));
        for(int i=0;i<nb;i++)
        {
            JButton jb=new JButton();
            Joueur j = lj.getJoueur(i);
            jb.setName(""+i);//on fixe comme name du bouton son numéro
            //on abonne le bouton à un écouteur (cliquable)
            jb.addActionListener(new ActionListener()
            {public void actionPerformed(ActionEvent evt)
            {
                AfficheInfosJoueur(evt);
            }
                
            });
            Panneau.add(jb);
        }
        this.pack();
    }
    
    private void afficheTrombi(){
        for(int i=0;i<this.lj.getNbJoueurs();i++ )
        {   //on récupère le ième bouton
            JButton jb = (JButton)Panneau.getComponent(i);
            Joueur j = this.lj.getJoueur(i);//récupère le joueur d'indice i
            Image img=j.getPhoto().getImage().getScaledInstance(jb.getWidth(),jb.getHeight(),Image.SCALE_DEFAULT);
            jb.setIcon(new ImageIcon(img));
          
        }
     
    }
    
    private void AfficheInfosJoueur(ActionEvent evt){            
            
           int nb = this.lj.getNbJoueurs();
           for(int i=0;i<nb;i++){
               JButton jb = (JButton)Panneau.getComponent(i);
               Joueur j = this.lj.getJoueur(i);
               if(evt.getSource().equals(jb))
                   Edition.setText(j.toString());
           }
    
            
           
           
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Afficher = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        Panneau = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setText("Choisissez un joueur pour voir ses caractéristiques");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        Afficher.setText("Afficher");
        Afficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherActionPerformed(evt);
            }
        });
        jPanel2.add(Afficher, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        Edition.setColumns(20);
        Edition.setRows(5);
        Edition.setPreferredSize(new java.awt.Dimension(536, 464));
        jScrollPane1.setViewportView(Edition);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.EAST);

        Panneau.setLayout(new java.awt.GridLayout(1, 2));
        getContentPane().add(Panneau, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherActionPerformed
         afficheTrombi();
        
    }//GEN-LAST:event_AfficherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisuJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisuJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisuJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisuJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VisuJoueursDlg dialog = new VisuJoueursDlg(new javax.swing.JFrame(), true ,new LesJoueurs());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Afficher;
    private javax.swing.JTextArea Edition;
    private javax.swing.JPanel Panneau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
